### PR TITLE
Added capability to use connection strings from config file

### PR DESCRIPTION
**Pull request by ammachado**
Instead of declaring the URL on the config method call.  Also, it becomes easier to configure via <appSettings>.

### CODE REVIEW

**Comment by Jaben** [comment]
Good idea!

@nblumhardt What do you think? Any convention for this type of thing in other sinks?

**Comment by nblumhardt** [comment]
Interesting! In the SQL Server sink the param is just called `connectionString`.

I guess the main stumbling block is what to do with the `databaseUrl` parameter on: https://github.com/serilog/serilog-sinks-mongodb/blob/dev/src/Serilog.Sinks.MongoDB/LoggerConfigurationMongoDBExtensions.cs#L41

If we change it we'll break existing configs, but leaving it as-is seems misleading if it is also treated as a connection string name. Need to give it some thought, might be some trick we can use....

**Comment by Jaben** [comment]
@nblumhardt The parameter name change would break existing configurations? Is this for AppSettings loader or just where people are using optional parameters?

**Comment by nblumhardt** [comment]
@Jaben the <appSettings> one is the primary concern because of the lack of compile-time checking, and the absence of a runtime exception; the parameter name itself's not such a worry because binary compatibility will still be maintained.

**Comment by Jaben** [comment]
@nblumhardt Maybe a minor change to Serilog AppSettings that allows forwarding settings to another value with a warning with an Attribute?

**Comment by Jaben** [comment]
@nblumhardt another option is make a tiny change to KeyValuePairSettings.FindConfigurationMethods to allow finding private extension methods (e.g. .Where(m => m.IsStatic && (m.IsPublic || m.IsPrivate) && m.IsDefined(typeof(ExtensionAttribute), false)). Then we can create "redirection" extensions.

**Comment by nblumhardt** [comment]
👍 :-)

**Pull request merged**
