### PR TITLE
Replacing reserved characters in the key field of the Bson document.

### PR DESCRIPTION
**Pull request by IcanBENCHurCAT**
We have been dealing with the issue documented [here](https://github.com/serilog/serilog-sinks-mongodb/issues/29)

This has been tested to work in our dotnet core application.

### CODE REVIEW

**Comment by IcanBENCHurCAT** [comment]
@nblumhardt any chance you could take a look at this?

**Comment by nblumhardt** [comment]
LGTM! Thanks 👍

**Comment by IcanBENCHurCAT** [comment]
@nblumhardt Any idea when we can see this in a pre-release package? Trying to make some updates back to my team on the status of this bug in our product.

**Comment by nblumhardt** [comment]
Hi @IcanBENCHurCAT - this already went out as `4.0.0-dev-00068` - unfortunately the build numbering was wrong and so it shows up as an older release :-) ... I've just updated the version to 4.1 and kicked off a new build, hopefully that will be out shortly. Cheers!

**Pull request merged**
